package com.equipment.maintenance;

import com.equipment.audit.Audit;
import com.equipment.common.*;
import com.equipment.finance.FinanceService;
import com.equipment.identity.Actor;
import com.equipment.workspaces.Access;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.json.JsonMapper;

@Service
public class MaintenanceService {
    private static final Set<String> ISSUE_TYPES=Set.of("MECHANICAL","ELECTRICAL","TIRES","ACCIDENT_DAMAGE","OTHER");
    private static final Set<String> MAINTENANCE_TYPES=Set.of("REPAIR","PERIODIC_SERVICE","INSPECTION","OTHER");
    private static final JsonMapper JSON=JsonMapper.builder().build();
    private final JdbcTemplate db; private final Access access; private final Audit audit; private final Idempotency retries; private final FinanceService finance;
    public MaintenanceService(JdbcTemplate db,Access access,Audit audit,Idempotency retries,FinanceService finance){this.db=db;this.access=access;this.audit=audit;this.retries=retries;this.finance=finance;}
    public record IssueInput(String description,String type,Boolean equipmentStopped) {}
    public record CloseInput(String resolution) {}
    public record MaintenanceInput(String description,String maintenanceDate,String type,String workshop,UUID issueId) {}
    public record CancelInput(String reason) {}
    private String optionalType(String type,Set<String> allowed){if(type!=null && !allowed.contains(type))throw ApiException.invalid("النوع غير صالح");return type;}
    private String description(String raw){return Values.text(raw,2000,"الوصف");}
    private String workshop(String raw){return raw==null || raw.isBlank()?null:Values.text(raw,200,"اسم الورشة");}
    private void equipment(UUID w,UUID id,boolean active){var rows=db.queryForList("select archived_at from equipment where workspace_id=? and id=?"+(active?" for update":""),w,id);if(rows.isEmpty())throw ApiException.missing();if(active && rows.getFirst().get("archived_at")!=null)throw new ApiException(409,"EQUIPMENT_ARCHIVED","استعد المعدة أولًا");}
    private Map<String,Object> issue(UUID w,UUID id,boolean lock){var rows=db.queryForList("select i.*,e.name as equipment_name,e.archived_at as equipment_archived_at from equipment_issue i join equipment e on e.workspace_id=i.workspace_id and e.id=i.equipment_id where i.workspace_id=? and i.id=?"+(lock?" for update of i":""),w,id);if(rows.isEmpty())throw ApiException.missing();return rows.getFirst();}
    private Map<String,Object> maintenance(UUID w,UUID id,boolean lock){var rows=db.queryForList("select m.*,e.name as equipment_name,e.archived_at as equipment_archived_at from maintenance_record m join equipment e on e.workspace_id=m.workspace_id and e.id=m.equipment_id where m.workspace_id=? and m.id=?"+(lock?" for update of m":""),w,id);if(rows.isEmpty())throw ApiException.missing();return rows.getFirst();}
    private String stamp(Object t){return t==null?null:((Timestamp)t).toInstant().toString();}
    private Map<String,Object> issueView(Map<String,Object> r,boolean detail){Map<String,Object> v=new LinkedHashMap<>();UUID id=(UUID)r.get("id"),w=(UUID)r.get("workspace_id");
        v.put("id",id);v.put("reference","IS-"+String.format("%06d",((Number)r.get("reference")).longValue()));v.put("equipmentId",r.get("equipment_id"));v.put("equipmentName",r.get("equipment_name"));v.put("description",r.get("description"));v.put("type",r.get("type"));v.put("equipmentStopped",r.get("equipment_stopped"));v.put("status",r.get("status"));v.put("resolution",r.get("resolution"));v.put("closedAt",stamp(r.get("closed_at")));v.put("closedBy",r.get("closed_by"));v.put("createdAt",stamp(r.get("created_at")));v.put("createdBy",r.get("created_by"));v.put("equipmentArchived",r.get("equipment_archived_at")!=null);
        if(detail){v.put("closures",db.queryForList("select id,resolution,closed_at as \"closedAt\",closed_by as \"closedBy\",reopened_at as \"reopenedAt\",reopened_by as \"reopenedBy\" from issue_closure where workspace_id=? and issue_id=? order by closed_at desc",w,id));v.put("maintenance",db.queryForList("select id,description,maintenance_date::text as \"maintenanceDate\",cancelled_at as \"cancelledAt\" from maintenance_record where workspace_id=? and issue_id=? order by maintenance_date desc,id desc",w,id));}return v;}
    public Map<String,Object> getIssue(Actor actor,UUID w,UUID id){access.owner(actor,w);return issueView(issue(w,id,false),true);}
    private static void page(int page){if(page<0 || page>100000)throw ApiException.invalid("رقم الصفحة غير صالح");}
    private String like(String s){if(s==null)return null;String t=s.trim();if(t.length()>100)throw ApiException.invalid("اختصر نص البحث");return "%"+t.replace("\\","\\\\").replace("%","\\%").replace("_","\\_")+"%";}
    public Map<String,Object> listIssues(Actor actor,UUID w,UUID equipmentId,String status,Boolean stopped,String from,String to,String search,int page){access.owner(actor,w);page(page);if(equipmentId!=null)equipment(w,equipmentId,false);if(status!=null && !Set.of("OPEN","IN_PROGRESS","CLOSED").contains(status))throw ApiException.invalid("الحالة غير صالحة");
        StringBuilder where=new StringBuilder(" where i.workspace_id=?");List<Object> args=new ArrayList<>(List.of(w));if(equipmentId!=null){where.append(" and i.equipment_id=?");args.add(equipmentId);}if(status!=null){where.append(" and i.status=?");args.add(status);}if(stopped!=null){where.append(" and i.equipment_stopped=?");args.add(stopped);}if(from!=null){where.append(" and i.created_at::date>=?");args.add(java.sql.Date.valueOf(Values.date(from)));}if(to!=null){where.append(" and i.created_at::date<=?");args.add(java.sql.Date.valueOf(Values.date(to)));}String term=like(search);if(term!=null){where.append(" and (i.description ilike ? escape '\\' or e.name ilike ? escape '\\' or ('IS-'||lpad(i.reference::text,6,'0')) ilike ? escape '\\' or i.type ilike ? escape '\\')");Collections.addAll(args,term,term,term,term);}
        String join=" from equipment_issue i join equipment e on e.workspace_id=i.workspace_id and e.id=i.equipment_id";Long total=db.queryForObject("select count(*)"+join+where,Long.class,args.toArray());args.add(page*30);var rows=db.queryForList("select i.*,e.name as equipment_name,e.archived_at as equipment_archived_at"+join+where+" order by case i.status when 'OPEN' then 0 when 'IN_PROGRESS' then 1 else 2 end,i.created_at desc,i.id desc limit 30 offset ?",args.toArray());return Map.of("items",rows.stream().map(r->issueView(r,false)).toList(),"page",page,"pageSize",30,"total",total);}
    @Transactional public Map<String,Object> createIssue(Actor actor,UUID w,UUID equipmentId,String key,IssueInput input){access.owner(actor,w);equipment(w,equipmentId,true);if(input==null)throw ApiException.invalid("أدخل البلاغ");String d=description(input.description()),t=optionalType(input.type(),ISSUE_TYPES);boolean stopped=Boolean.TRUE.equals(input.equipmentStopped());UUID id=retries.execute(w,actor.userId(),"issue.create:"+equipmentId,key,Values.payload(d,t,stopped),()->{UUID created=UUID.randomUUID();db.update("insert into equipment_issue(id,workspace_id,equipment_id,description,type,equipment_stopped,created_by) values(?,?,?,?,?,?,?)",created,w,equipmentId,d,t,stopped,actor.userId());audit.record(w,actor.userId(),"ISSUE_CREATED",created);return created;});return getIssue(actor,w,id);}
    @Transactional public Map<String,Object> editIssue(Actor actor,UUID w,UUID id,IssueInput input){access.owner(actor,w);var old=issue(w,id,true);if(!"OPEN".equals(old.get("status")) && !"IN_PROGRESS".equals(old.get("status")))throw new ApiException(409,"ISSUE_CLOSED","أعد فتح البلاغ قبل تعديله");if(input==null)throw ApiException.invalid("أدخل البلاغ");String d=description(input.description()),t=optionalType(input.type(),ISSUE_TYPES);boolean stopped=Boolean.TRUE.equals(input.equipmentStopped());db.update("update equipment_issue set description=?,type=?,equipment_stopped=?,updated_at=now() where workspace_id=? and id=?",d,t,stopped,w,id);audit.record(w,actor.userId(),"ISSUE_UPDATED",id,JSON.writeValueAsString(Map.of("beforeDescription",old.get("description"),"afterDescription",d,"beforeStopped",old.get("equipment_stopped"),"afterStopped",stopped)));return getIssue(actor,w,id);}
    @Transactional public Map<String,Object> start(Actor actor,UUID w,UUID id){access.owner(actor,w);var old=issue(w,id,true);if(!"OPEN".equals(old.get("status")))throw new ApiException(409,"ISSUE_STATE","لا يمكن بدء معالجة هذا البلاغ");db.update("update equipment_issue set status='IN_PROGRESS',updated_at=now() where workspace_id=? and id=?",w,id);audit.record(w,actor.userId(),"ISSUE_STARTED",id);return getIssue(actor,w,id);}
    @Transactional public Map<String,Object> close(Actor actor,UUID w,UUID id,CloseInput input){access.owner(actor,w);var old=issue(w,id,true);if("CLOSED".equals(old.get("status")))throw new ApiException(409,"ISSUE_STATE","البلاغ مغلق بالفعل");String resolution=Values.text(input==null?null:input.resolution(),2000,"ما تم");UUID closure=UUID.randomUUID();db.update("update equipment_issue set status='CLOSED',resolution=?,closed_at=now(),closed_by=?,updated_at=now() where workspace_id=? and id=?",resolution,actor.userId(),w,id);db.update("insert into issue_closure(id,workspace_id,issue_id,resolution,closed_at,closed_by) values(?,?,?,?,now(),?)",closure,w,id,resolution,actor.userId());audit.record(w,actor.userId(),"ISSUE_CLOSED",id,JSON.writeValueAsString(Map.of("resolution",resolution,"closureId",closure)));return getIssue(actor,w,id);}
    @Transactional public Map<String,Object> reopen(Actor actor,UUID w,UUID id){access.owner(actor,w);var old=issue(w,id,true);if(!"CLOSED".equals(old.get("status")))throw new ApiException(409,"ISSUE_STATE","البلاغ غير مغلق");db.update("update issue_closure set reopened_at=now(),reopened_by=? where workspace_id=? and issue_id=? and reopened_at is null",actor.userId(),w,id);db.update("update equipment_issue set status='OPEN',resolution=null,closed_at=null,closed_by=null,updated_at=now() where workspace_id=? and id=?",w,id);audit.record(w,actor.userId(),"ISSUE_REOPENED",id,JSON.writeValueAsString(Map.of("previousResolution",old.get("resolution"))));return getIssue(actor,w,id);}
    private Map<String,Object> maintenanceView(Map<String,Object> r,boolean detail){UUID w=(UUID)r.get("workspace_id"),id=(UUID)r.get("id");Map<String,Object> v=new LinkedHashMap<>();v.put("id",id);v.put("equipmentId",r.get("equipment_id"));v.put("equipmentName",r.get("equipment_name"));v.put("issueId",r.get("issue_id"));v.put("description",r.get("description"));v.put("maintenanceDate",r.get("maintenance_date").toString());v.put("type",r.get("type"));v.put("workshop",r.get("workshop"));v.put("cancelledAt",stamp(r.get("cancelled_at")));v.put("cancellationReason",r.get("cancellation_reason"));v.put("createdAt",stamp(r.get("created_at")));v.put("equipmentArchived",r.get("equipment_archived_at")!=null);if(detail){List<FinanceService.Entry> expenses=db.query("select entry_id from maintenance_expense_link where workspace_id=? and maintenance_id=? order by linked_at,entry_id",(rs,n)->finance.require(w,rs.getObject(1,UUID.class)),w,id);v.put("expenses",expenses);BigDecimal amount=BigDecimal.ZERO,net=BigDecimal.ZERO,remaining=BigDecimal.ZERO;int active=0;for(var e:expenses)if("POSTED".equals(e.lifecycle())){active++;amount=amount.add(new BigDecimal(e.amount()));net=net.add(new BigDecimal(e.netPaid()));remaining=remaining.add(new BigDecimal(e.remaining()));}v.put("financialSummary",Map.of("linkedExpenseCount",expenses.size(),"activeExpenseCount",active,"totalActiveExpenseAmount",amount.setScale(2).toPlainString(),"netPaid",net.setScale(2).toPlainString(),"remaining",remaining.setScale(2).toPlainString()));}return v;}
    public Map<String,Object> getMaintenance(Actor actor,UUID w,UUID id){access.owner(actor,w);return maintenanceView(maintenance(w,id,false),true);}
    public Map<String,Object> listMaintenance(Actor actor,UUID w,UUID equipmentId,String type,Boolean cancelled,String from,String to,String search,int page){access.owner(actor,w);page(page);if(equipmentId!=null)equipment(w,equipmentId,false);optionalType(type,MAINTENANCE_TYPES);StringBuilder where=new StringBuilder(" where m.workspace_id=?");List<Object> args=new ArrayList<>(List.of(w));if(equipmentId!=null){where.append(" and m.equipment_id=?");args.add(equipmentId);}if(type!=null){where.append(" and m.type=?");args.add(type);}if(!Boolean.TRUE.equals(cancelled)){where.append(" and m.cancelled_at is null");}else{where.append(" and m.cancelled_at is not null");}if(from!=null){where.append(" and m.maintenance_date>=?");args.add(java.sql.Date.valueOf(Values.date(from)));}if(to!=null){where.append(" and m.maintenance_date<=?");args.add(java.sql.Date.valueOf(Values.date(to)));}String term=like(search);if(term!=null){where.append(" and (m.description ilike ? escape '\\' or m.workshop ilike ? escape '\\' or e.name ilike ? escape '\\')");Collections.addAll(args,term,term,term);}String join=" from maintenance_record m join equipment e on e.workspace_id=m.workspace_id and e.id=m.equipment_id";Long total=db.queryForObject("select count(*)"+join+where,Long.class,args.toArray());args.add(page*30);var rows=db.queryForList("select m.*,e.name as equipment_name,e.archived_at as equipment_archived_at"+join+where+" order by m.maintenance_date desc,m.id desc limit 30 offset ?",args.toArray());return Map.of("items",rows.stream().map(r->maintenanceView(r,false)).toList(),"page",page,"pageSize",30,"total",total);}
    private void issueMatch(UUID w,UUID equipmentId,UUID issueId){if(issueId!=null && !equipmentId.equals(issue(w,issueId,false).get("equipment_id")))throw ApiException.invalid("البلاغ لمعدة مختلفة");}
    @Transactional public Map<String,Object> createMaintenance(Actor actor,UUID w,UUID equipmentId,String key,MaintenanceInput input){access.owner(actor,w);equipment(w,equipmentId,true);if(input==null)throw ApiException.invalid("أدخل الصيانة");String d=description(input.description()),t=optionalType(input.type(),MAINTENANCE_TYPES),shop=workshop(input.workshop());LocalDate date=Values.date(input.maintenanceDate());issueMatch(w,equipmentId,input.issueId());UUID id=retries.execute(w,actor.userId(),"maintenance.create:"+equipmentId,key,Values.payload(d,date,t,shop,input.issueId()),()->{UUID created=UUID.randomUUID();db.update("insert into maintenance_record(id,workspace_id,equipment_id,issue_id,description,maintenance_date,type,workshop,created_by) values(?,?,?,?,?,?,?,?,?)",created,w,equipmentId,input.issueId(),d,java.sql.Date.valueOf(date),t,shop,actor.userId());audit.record(w,actor.userId(),"MAINTENANCE_CREATED",created);return created;});return getMaintenance(actor,w,id);}
    @Transactional public Map<String,Object> editMaintenance(Actor actor,UUID w,UUID id,MaintenanceInput input){access.owner(actor,w);var old=maintenance(w,id,true);if(old.get("cancelled_at")!=null)throw new ApiException(409,"MAINTENANCE_CANCELLED","سجل الصيانة ملغى");if(input==null)throw ApiException.invalid("أدخل الصيانة");String d=description(input.description()),t=optionalType(input.type(),MAINTENANCE_TYPES),shop=workshop(input.workshop());LocalDate date=Values.date(input.maintenanceDate());issueMatch(w,(UUID)old.get("equipment_id"),input.issueId());db.update("update maintenance_record set description=?,maintenance_date=?,type=?,workshop=?,issue_id=?,updated_at=now() where workspace_id=? and id=?",d,java.sql.Date.valueOf(date),t,shop,input.issueId(),w,id);audit.record(w,actor.userId(),"MAINTENANCE_UPDATED",id,JSON.writeValueAsString(Map.of("beforeDescription",old.get("description"),"afterDescription",d)));return getMaintenance(actor,w,id);}
    @Transactional public Map<String,Object> cancelMaintenance(Actor actor,UUID w,UUID id,CancelInput input){access.owner(actor,w);var old=maintenance(w,id,true);if(old.get("cancelled_at")!=null)throw new ApiException(409,"MAINTENANCE_CANCELLED","سجل الصيانة ملغى");String reason=Values.text(input==null?null:input.reason(),1000,"سبب الإلغاء");db.update("update maintenance_record set cancelled_at=now(),cancelled_by=?,cancellation_reason=?,updated_at=now() where workspace_id=? and id=?",actor.userId(),reason,w,id);audit.record(w,actor.userId(),"MAINTENANCE_CANCELLED",id,JSON.writeValueAsString(Map.of("reason",reason)));return getMaintenance(actor,w,id);}
    private void eligible(UUID w,UUID maintenanceId,UUID entryId){var m=maintenance(w,maintenanceId,true);if(m.get("cancelled_at")!=null)throw new ApiException(409,"MAINTENANCE_CANCELLED","سجل الصيانة ملغى");var rows=db.queryForList("select equipment_id,entry_type,expense_scope,lifecycle from financial_entry where workspace_id=? and id=? for update",w,entryId);if(rows.isEmpty())throw ApiException.missing();var e=rows.getFirst();if(!"EXPENSE".equals(e.get("entry_type")) || !"SINGLE".equals(e.get("expense_scope")) || !"POSTED".equals(e.get("lifecycle")) || !Objects.equals(e.get("equipment_id"),m.get("equipment_id")))throw ApiException.invalid("المصروف غير مؤهل لهذا السجل");}
    @Transactional public Map<String,Object> linkExpense(Actor actor,UUID w,UUID id,UUID entryId){access.owner(actor,w);eligible(w,id,entryId);var rows=db.queryForList("select maintenance_id from maintenance_expense_link where workspace_id=? and entry_id=?",w,entryId);if(!rows.isEmpty()){if(id.equals(rows.getFirst().get("maintenance_id")))return getMaintenance(actor,w,id);throw new ApiException(409,"EXPENSE_ALREADY_LINKED","المصروف مرتبط بسجل صيانة آخر");}db.update("insert into maintenance_expense_link(workspace_id,maintenance_id,entry_id,linked_by) values(?,?,?,?)",w,id,entryId,actor.userId());audit.record(w,actor.userId(),"MAINTENANCE_EXPENSE_LINKED",id,JSON.writeValueAsString(Map.of("entryId",entryId)));return getMaintenance(actor,w,id);}
    @Transactional public Map<String,Object> createExpense(Actor actor,UUID w,UUID id,String key,FinanceService.Create input){access.owner(actor,w);var m=maintenance(w,id,true);if(m.get("cancelled_at")!=null)throw new ApiException(409,"MAINTENANCE_CANCELLED","سجل الصيانة ملغى");if(input==null || !Objects.equals(input.equipmentId(),m.get("equipment_id")) || (input.entryType()!=null && !"EXPENSE".equals(input.entryType())) || (input.expenseScope()!=null && !"SINGLE".equals(input.expenseScope())) || input.allocations()!=null)throw ApiException.invalid("اختر مصروفًا منفردًا للمعدة نفسها");FinanceService.Entry entry=finance.create(actor,w,key,input);return linkExpense(actor,w,id,entry.id());}
    @Transactional public Map<String,Object> unlinkExpense(Actor actor,UUID w,UUID id,UUID entryId){access.owner(actor,w);var record=maintenance(w,id,true);if(record.get("cancelled_at")!=null)throw new ApiException(409,"MAINTENANCE_CANCELLED","سجل الصيانة ملغى");int changed=db.update("delete from maintenance_expense_link where workspace_id=? and maintenance_id=? and entry_id=?",w,id,entryId);if(changed==0)throw ApiException.missing();audit.record(w,actor.userId(),"MAINTENANCE_EXPENSE_UNLINKED",id,JSON.writeValueAsString(Map.of("entryId",entryId)));return getMaintenance(actor,w,id);}
    public Map<String,Object> eligibleExpenses(Actor actor,UUID w,UUID id,String search,int page){access.owner(actor,w);page(page);var m=maintenance(w,id,false);String term=like(search);String where=" where f.workspace_id=? and f.equipment_id=? and f.entry_type='EXPENSE' and f.expense_scope='SINGLE' and f.lifecycle='POSTED' and not exists(select 1 from maintenance_expense_link l where l.workspace_id=f.workspace_id and l.entry_id=f.id)"+(term==null?"":" and (f.note ilike ? escape '\\' or f.category ilike ? escape '\\')");List<Object> args=new ArrayList<>(List.of(w,m.get("equipment_id")));if(term!=null)Collections.addAll(args,term,term);Long total=db.queryForObject("select count(*) from financial_entry f"+where,Long.class,args.toArray());args.add(page*30);List<FinanceService.Entry> items=db.query("select f.id from financial_entry f"+where+" order by f.operation_date desc,f.created_at desc limit 30 offset ?",(rs,n)->finance.require(w,rs.getObject(1,UUID.class)),args.toArray());return Map.of("items",items,"page",page,"pageSize",30,"total",total);}
    public void requireIssue(UUID w,UUID id){issue(w,id,false);} public void requireMaintenance(UUID w,UUID id){maintenance(w,id,false);}
}
