-- Add M6 defaults only to memberships and pending invitations retaining the exact M5 role template.
-- Customized capability sets remain unchanged.
UPDATE membership SET capabilities=capabilities||ARRAY['ORGANIZATION_VIEW','ORGANIZATION_MANAGE','PROJECT_VIEW','PROJECT_MANAGE']::text[]
WHERE role='MANAGER' AND cardinality(capabilities)=13 AND capabilities @> ARRAY[
 'EQUIPMENT_VIEW','EQUIPMENT_MANAGE','FINANCE_VIEW','FINANCE_MANAGE','FINANCE_REVIEW',
 'DOCUMENT_VIEW','DOCUMENT_MANAGE','ISSUE_VIEW','ISSUE_MANAGE',
 'MAINTENANCE_VIEW','MAINTENANCE_MANAGE','DRIVER_ASSIGNMENT_MANAGE','REPORT_VIEW']::text[];
UPDATE membership SET capabilities=capabilities||ARRAY['ORGANIZATION_VIEW','PROJECT_VIEW']::text[]
WHERE role='ACCOUNTANT' AND cardinality(capabilities)=11 AND capabilities @> ARRAY[
 'EQUIPMENT_VIEW','FINANCE_VIEW','FINANCE_MANAGE','FINANCE_REVIEW',
 'DOCUMENT_VIEW','DOCUMENT_MANAGE','ISSUE_VIEW','ISSUE_MANAGE',
 'MAINTENANCE_VIEW','MAINTENANCE_MANAGE','REPORT_VIEW']::text[];
UPDATE workspace_invitation SET capabilities=capabilities||ARRAY['ORGANIZATION_VIEW','ORGANIZATION_MANAGE','PROJECT_VIEW','PROJECT_MANAGE']::text[]
WHERE role='MANAGER' AND status='PENDING' AND cardinality(capabilities)=13 AND capabilities @> ARRAY[
 'EQUIPMENT_VIEW','EQUIPMENT_MANAGE','FINANCE_VIEW','FINANCE_MANAGE','FINANCE_REVIEW',
 'DOCUMENT_VIEW','DOCUMENT_MANAGE','ISSUE_VIEW','ISSUE_MANAGE',
 'MAINTENANCE_VIEW','MAINTENANCE_MANAGE','DRIVER_ASSIGNMENT_MANAGE','REPORT_VIEW']::text[];
UPDATE workspace_invitation SET capabilities=capabilities||ARRAY['ORGANIZATION_VIEW','PROJECT_VIEW']::text[]
WHERE role='ACCOUNTANT' AND status='PENDING' AND cardinality(capabilities)=11 AND capabilities @> ARRAY[
 'EQUIPMENT_VIEW','FINANCE_VIEW','FINANCE_MANAGE','FINANCE_REVIEW',
 'DOCUMENT_VIEW','DOCUMENT_MANAGE','ISSUE_VIEW','ISSUE_MANAGE',
 'MAINTENANCE_VIEW','MAINTENANCE_MANAGE','REPORT_VIEW']::text[];
