package com.equipment.finance;

import com.equipment.audit.Audit;
import com.equipment.attachments.*;
import com.equipment.common.*;
import com.equipment.identity.Actor;
import com.equipment.notifications.NotificationService;
import com.equipment.workspaces.*;
import java.math.BigDecimal;
import java.io.IOException;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class SubmissionService {
    private final JdbcTemplate db;private final Access access;private final DriverService drivers;private final FinanceService finance;private final Audit audit;private final ObjectStorageService storage;private final ContentValidator validator;private final NotificationService notifications;
    public SubmissionService(JdbcTemplate db,Access access,DriverService drivers,FinanceService finance,Audit audit,ObjectStorageService storage,ContentValidator validator,NotificationService notifications){this.db=db;this.access=access;this.drivers=drivers;this.finance=finance;this.audit=audit;this.storage=storage;this.validator=validator;this.notifications=notifications;}
    public record Receipt(String filename,String mediaType,String base64){}
    public record Create(UUID equipmentId,String amount,String transactionDate,String note,Receipt receipt){}
    public record Reject(String reason){}
    private UUID submitEquipment(Actor actor,UUID w,UUID requested){Access.Member m=access.require(actor,w,"FINANCE_MANAGE");if(m.role().equals("DRIVER")){UUID current=drivers.requireCurrent(actor,w);if(requested!=null&&!current.equals(requested))throw ApiException.missing();return current;}if(requested==null)throw ApiException.invalid("اختر المعدة");access.equipment(actor,w,requested,"EQUIPMENT_VIEW");return requested;}
    @Transactional public Map<String,Object> create(Actor actor,UUID w,Create input){if(input==null)throw ApiException.invalid("أدخل الطلب");Access.Member m=access.require(actor,w,"FINANCE_MANAGE");if(!m.financialMode().equals("REVIEW"))throw ApiException.missing();UUID equipment=submitEquipment(actor,w,input.equipmentId());BigDecimal amount=input.amount()==null||input.amount().isBlank()?null:Values.money(input.amount());String note=input.note()==null?null:input.note().trim();if(note!=null&&note.length()>1000)throw ApiException.invalid("اختصر الملاحظة");LocalDate date=input.transactionDate()==null?LocalDate.now(ZoneId.of("Asia/Riyadh")):Values.date(input.transactionDate());if(amount==null&&(note==null||note.isEmpty())&&input.receipt()==null)throw ApiException.invalid("أضف مبلغًا أو ملاحظة أو مرفقًا");UUID id=UUID.randomUUID();db.update("insert into financial_submission(id,workspace_id,equipment_id,submitted_by,amount,transaction_date,note) values(?,?,?,?,?,?,?)",id,w,equipment,actor.userId(),amount,java.sql.Date.valueOf(date),note);if(input.receipt()!=null)receipt(actor,w,id,input.receipt());audit.record(w,actor.userId(),"FINANCIAL_SUBMISSION_CREATED",id);UUID owner=db.queryForObject("select owner_id from workspace where id=?",UUID.class,w);if(!actor.userId().equals(owner))notifications.event(w,owner,"SUBMISSION_PENDING","FINANCIAL_SUBMISSION",id,Map.of("submissionId",id));return view(w,id);}
    private void receipt(Actor actor,UUID w,UUID submission,Receipt receipt){String filename=Values.text(receipt.filename(),200,"اسم الملف");if(filename.contains("/")||filename.contains("\\"))throw ApiException.invalid("اسم الملف غير صالح");if(!ContentValidator.TYPES.contains(receipt.mediaType()))throw new ApiException(400,"UNSUPPORTED_FILE","صيغة الملف غير مدعومة");byte[] bytes;try{bytes=Base64.getDecoder().decode(receipt.base64());}catch(RuntimeException e){throw ApiException.invalid("المرفق غير صالح");}if(bytes.length==0||bytes.length>ContentValidator.MAX_BYTES)throw new ApiException(413,"FILE_TOO_LARGE","الملف أكبر من الحد المسموح");String verified=validator.validate(bytes,receipt.mediaType()),hash=Values.hash(bytes);UUID id=UUID.randomUUID();String key=w+"/"+id+"/"+hash;try{storage.putImmutable(key,bytes);}catch(IOException e){throw new ApiException(503,"UPLOAD_FAILED","تعذر حفظ المرفق");}db.update("insert into attachment(id,workspace_id,submission_id,original_name,declared_type,declared_size,verified_type,actual_size,checksum,object_key,state,created_by) values(?,?,?,?,?,?,?,?,?,?,'READY',?)",id,w,submission,filename,receipt.mediaType(),bytes.length,verified,bytes.length,hash,key,actor.userId());}
    private Map<String,Object> present(Map<String,Object> row){Map<String,Object> result=new LinkedHashMap<>();row.forEach((key,value)->{StringBuilder name=new StringBuilder();boolean upper=false;for(char c:key.toCharArray()){if(c=='_'){upper=true;continue;}name.append(upper?Character.toUpperCase(c):c);upper=false;}Object output=value instanceof java.sql.Timestamp timestamp?timestamp.toInstant().toString():value instanceof java.sql.Date date?date.toString():value instanceof BigDecimal amount?amount.setScale(2).toPlainString():value;result.put(name.toString(),output);});return result;}
    private Map<String,Object> view(UUID w,UUID id){var rows=db.queryForList("select s.id,s.workspace_id,s.equipment_id,e.name as equipment_name,s.submitted_by,u.name as submitter_name,s.amount,s.transaction_date,s.note,s.status,s.submitted_at,s.reviewed_by,s.reviewed_at,s.rejection_reason,s.approved_financial_entry_id,s.resubmitted_from_submission_id from financial_submission s join equipment e on e.workspace_id=s.workspace_id and e.id=s.equipment_id join app_user u on u.id=s.submitted_by where s.workspace_id=? and s.id=?",w,id);if(rows.isEmpty())throw ApiException.missing();Map<String,Object> result=present(rows.getFirst());result.put("attachments",db.queryForList("select id,original_name as filename,verified_type as media_type,actual_size as size from attachment where workspace_id=? and submission_id=? and state='READY'",w,id).stream().map(this::present).toList());return result;}
    private Map<String,Object> row(Actor actor,UUID w,UUID id){access.member(actor,w);Map<String,Object> row=view(w,id);if(actor.userId().equals(row.get("submittedBy")))return row;Access.Member m=access.require(actor,w,"FINANCE_REVIEW");if(!access.contains(m,w,(UUID)row.get("equipmentId")))throw ApiException.missing();return row;}
    public Map<String,Object> get(Actor actor,UUID w,UUID id){return row(actor,w,id);}
    @Transactional public Map<String,Object> resubmit(Actor actor,UUID w,UUID original){
        access.member(actor,w);
        var rows=db.queryForList("select * from financial_submission where workspace_id=? and id=? and submitted_by=? for update",w,original,actor.userId());
        if(rows.isEmpty())throw ApiException.missing();
        var source=rows.getFirst();
        if(!"REJECTED".equals(source.get("status")))throw new ApiException(409,"SUBMISSION_NOT_REJECTED","يمكن إعادة إرسال الطلب المرفوض فقط");
        Access.Member member=access.require(actor,w,"FINANCE_MANAGE");
        if(!"REVIEW".equals(member.financialMode())||!((UUID)source.get("equipment_id")).equals(submitEquipment(actor,w,(UUID)source.get("equipment_id"))))throw ApiException.missing();
        var prior=db.queryForList("select id from financial_submission where workspace_id=? and resubmitted_from_submission_id=?",w,original);
        if(!prior.isEmpty())return view(w,(UUID)prior.getFirst().get("id"));
        UUID id=UUID.randomUUID();
        db.update("insert into financial_submission(id,workspace_id,equipment_id,submitted_by,amount,transaction_date,note,resubmitted_from_submission_id) values(?,?,?,?,?,?,?,?)",id,w,source.get("equipment_id"),actor.userId(),source.get("amount"),source.get("transaction_date"),source.get("note"),original);
        db.update("insert into attachment(id,workspace_id,submission_id,original_name,declared_type,declared_size,verified_type,actual_size,checksum,object_key,state,created_by) select gen_random_uuid(),workspace_id,?,original_name,declared_type,declared_size,verified_type,actual_size,checksum,object_key,state,? from attachment where workspace_id=? and submission_id=? and state='READY'",id,actor.userId(),w,original);
        audit.record(w,actor.userId(),"FINANCIAL_SUBMISSION_RESUBMITTED",id);
        UUID owner=db.queryForObject("select owner_id from workspace where id=?",UUID.class,w);
        if(!actor.userId().equals(owner))notifications.event(w,owner,"SUBMISSION_PENDING","FINANCIAL_SUBMISSION",id,Map.of("submissionId",id));
        return view(w,id);
    }
    public Map<String,Object> own(Actor actor,UUID w,int page){access.member(actor,w);if(page<0||page>100000)throw ApiException.invalid("رقم الصفحة غير صالح");var rows=db.queryForList("select id from financial_submission where workspace_id=? and submitted_by=? order by submitted_at desc,id desc limit 30 offset ?",w,actor.userId(),page*30);Long total=db.queryForObject("select count(*) from financial_submission where workspace_id=? and submitted_by=?",Long.class,w,actor.userId());return Map.of("items",rows.stream().map(r->view(w,(UUID)r.get("id"))).toList(),"page",page,"pageSize",30,"total",total);}
    public Map<String,Object> queue(Actor actor,UUID w,int page){Access.Member m=access.require(actor,w,"FINANCE_REVIEW");if(page<0||page>100000)throw ApiException.invalid("رقم الصفحة غير صالح");String scope=m.scope().equals("ALL_EQUIPMENT")?"":m.scope().equals("ASSIGNED_EQUIPMENT")?" and exists(select 1 from driver_assignment d where d.workspace_id=s.workspace_id and d.equipment_id=s.equipment_id and d.driver_user_id=? and d.ended_at is null)":" and exists(select 1 from membership_equipment me where me.workspace_id=s.workspace_id and me.equipment_id=s.equipment_id and me.user_id=?)";Object[] count=scope.isEmpty()?new Object[]{w}:new Object[]{w,actor.userId()};Object[] list=scope.isEmpty()?new Object[]{w,page*30}:new Object[]{w,actor.userId(),page*30};Long total=db.queryForObject("select count(*) from financial_submission s where s.workspace_id=? and s.status='PENDING_REVIEW'"+scope,Long.class,count);var ids=db.queryForList("select s.id from financial_submission s where s.workspace_id=? and s.status='PENDING_REVIEW'"+scope+" order by s.submitted_at desc,s.id desc limit 30 offset ?",list);return Map.of("items",ids.stream().map(r->view(w,(UUID)r.get("id"))).toList(),"page",page,"pageSize",30,"total",total);}
    private Map<String,Object> locked(Actor actor,UUID w,UUID id){Access.Member m=access.require(actor,w,"FINANCE_REVIEW");var rows=db.queryForList("select * from financial_submission where workspace_id=? and id=? for update",w,id);if(rows.isEmpty()||!access.contains(m,w,(UUID)rows.getFirst().get("equipment_id")))throw ApiException.missing();if(!"PENDING_REVIEW".equals(rows.getFirst().get("status")))throw new ApiException(409,"SUBMISSION_REVIEWED","تمت مراجعة هذا الطلب بالفعل");return rows.getFirst();}
    @Transactional public Map<String,Object> approve(Actor actor,UUID w,UUID id,FinanceService.Create input){Map<String,Object> row=locked(actor,w,id);UUID equipment=(UUID)row.get("equipment_id");if(input==null||!equipment.equals(input.equipmentId())||input.allocations()!=null||input.expenseScope()!=null&&!input.expenseScope().equals("SINGLE")||input.entryType()!=null&&!input.entryType().equals("EXPENSE"))throw ApiException.invalid("اعتمد مصروفًا منفردًا للمعدة الأصلية");FinanceService.Entry entry=finance.approveSubmission(actor,w,id.toString(),input);db.update("update financial_entry set submission_id=?,submitted_by=? where workspace_id=? and id=?",id,row.get("submitted_by"),w,entry.id());db.update("update attachment set entry_id=? where workspace_id=? and submission_id=? and state='READY'",entry.id(),w,id);db.update("update financial_submission set status='APPROVED',reviewed_by=?,reviewed_at=now(),approved_financial_entry_id=? where workspace_id=? and id=?",actor.userId(),entry.id(),w,id);audit.record(w,actor.userId(),"FINANCIAL_SUBMISSION_APPROVED",id);if(!actor.userId().equals(row.get("submitted_by")))notifications.event(w,(UUID)row.get("submitted_by"),"SUBMISSION_APPROVED","FINANCIAL_SUBMISSION",id,Map.of("submissionId",id));return view(w,id);}
    @Transactional public Map<String,Object> reject(Actor actor,UUID w,UUID id,Reject input){Map<String,Object> row=locked(actor,w,id);String reason=Values.text(input==null?null:input.reason(),500,"سبب الرفض");db.update("update financial_submission set status='REJECTED',reviewed_by=?,reviewed_at=now(),rejection_reason=? where workspace_id=? and id=?",actor.userId(),reason,w,id);audit.record(w,actor.userId(),"FINANCIAL_SUBMISSION_REJECTED",id);if(!actor.userId().equals(row.get("submitted_by")))notifications.event(w,(UUID)row.get("submitted_by"),"SUBMISSION_REJECTED","FINANCIAL_SUBMISSION",id,Map.of("submissionId",id));return view(w,id);}
}
