package com.equipment.projects;

import com.equipment.audit.Audit;
import com.equipment.common.*;
import com.equipment.identity.Actor;
import com.equipment.workspaces.Access;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class OrganizationService {
    private final JdbcTemplate db;private final Access access;private final Audit audit;
    public OrganizationService(JdbcTemplate db,Access access,Audit audit){this.db=db;this.access=access;this.audit=audit;}
    public record Input(String name,String identifier,String notes){}
    public record Assignment(UUID organizationId){}
    private Map<String,Object> row(UUID w,UUID id){var rows=db.queryForList("select o.*, (select count(*) from equipment_organization_assignment a where a.workspace_id=o.workspace_id and a.organization_id=o.id and a.ended_at is null) equipment_count,(select count(*) from project_or_contract p where p.workspace_id=o.workspace_id and p.organization_id=o.id and p.archived_at is null) project_count from organization o where o.workspace_id=? and o.id=?",w,id);if(rows.isEmpty())throw ApiException.missing();return rows.getFirst();}
    public Map<String,Object> get(Actor actor,UUID w,UUID id){Access.Member m=access.require(actor,w,"ORGANIZATION_VIEW");if(!access.organization(m,w,id))throw ApiException.missing();return row(w,id);}
    public List<Map<String,Object>> list(Actor actor,UUID w,boolean archived,String search){Access.Member m=access.require(actor,w,"ORGANIZATION_VIEW");String term=search==null?"":search.trim();if(term.length()>100)throw ApiException.invalid("اختصر البحث");return db.queryForList("select o.id,o.name,o.identifier,o.notes,o.archived_at,(select count(*) from equipment_organization_assignment a where a.workspace_id=o.workspace_id and a.organization_id=o.id and a.ended_at is null) equipment_count,(select count(*) from project_or_contract p where p.workspace_id=o.workspace_id and p.organization_id=o.id and p.archived_at is null) project_count from organization o where o.workspace_id=? and (o.archived_at is not null)=? and o.name ilike ? order by o.created_at desc limit 100",w,archived,"%"+term.replace("%","\\%").replace("_","\\_")+"%").stream().filter(r->access.organization(m,w,(UUID)r.get("id"))).toList();}
    @Transactional public Map<String,Object> create(Actor actor,UUID w,Input input){Access.Member m=access.require(actor,w,"ORGANIZATION_MANAGE");if(!m.scope().equals("ALL_EQUIPMENT"))throw ApiException.missing();if(input==null)throw ApiException.invalid("أدخل المؤسسة");UUID id=UUID.randomUUID();db.update("insert into organization(id,workspace_id,name,identifier,notes,created_by) values(?,?,?,?,?,?)",id,w,Values.text(input.name(),100,"اسم المؤسسة"),optional(input.identifier(),100),optional(input.notes(),1000),actor.userId());audit.record(w,actor.userId(),"ORGANIZATION_CREATED",id);return row(w,id);}
    @Transactional public Map<String,Object> edit(Actor actor,UUID w,UUID id,Input input){access.require(actor,w,"ORGANIZATION_MANAGE");if(!access.organization(access.member(actor,w),w,id))throw ApiException.missing();if(input==null)throw ApiException.invalid("أدخل المؤسسة");if(db.update("update organization set name=?,identifier=?,notes=? where workspace_id=? and id=? and archived_at is null",Values.text(input.name(),100,"اسم المؤسسة"),optional(input.identifier(),100),optional(input.notes(),1000),w,id)==0)throw ApiException.missing();audit.record(w,actor.userId(),"ORGANIZATION_UPDATED",id);return row(w,id);}
    private String optional(String value,int max){if(value==null||value.isBlank())return null;return Values.text(value,max,"النص");}
    @Transactional public Map<String,Object> archive(Actor actor,UUID w,UUID id){access.require(actor,w,"ORGANIZATION_MANAGE");if(!access.organization(access.member(actor,w),w,id))throw ApiException.missing();var current=db.queryForList("select archived_at from organization where workspace_id=? and id=? for update",w,id);if(current.isEmpty())throw ApiException.missing();if(current.getFirst().get("archived_at")!=null)return row(w,id);Long equipment=db.queryForObject("select count(*) from equipment_organization_assignment where workspace_id=? and organization_id=? and ended_at is null",Long.class,w,id),projects=db.queryForObject("select count(*) from project_or_contract where workspace_id=? and organization_id=? and archived_at is null",Long.class,w,id);if(equipment>0||projects>0)throw new ApiException(409,"ORGANIZATION_IN_USE","لا يمكن أرشفة المؤسسة: لديها "+equipment+" معدة معيّنة و"+projects+" مشروع/عقد غير مؤرشف. انقل المعدات أو أزل ارتباطها، ثم أرشف المشاريع والعقود.");db.update("update organization set archived_at=now() where workspace_id=? and id=? and archived_at is null",w,id);audit.record(w,actor.userId(),"ORGANIZATION_ARCHIVED",id);return row(w,id);}
    @Transactional public Map<String,Object> restore(Actor actor,UUID w,UUID id){access.require(actor,w,"ORGANIZATION_MANAGE");if(!access.organization(access.member(actor,w),w,id))throw ApiException.missing();row(w,id);db.update("update organization set archived_at=null where workspace_id=? and id=? and archived_at is not null",w,id);audit.record(w,actor.userId(),"ORGANIZATION_RESTORED",id);return row(w,id);}
    public List<Map<String,Object>> history(Actor actor,UUID w,UUID equipment){access.equipment(actor,w,equipment,"EQUIPMENT_VIEW");return db.queryForList("select id,organization_id,started_at,ended_at,assigned_by from equipment_organization_assignment where workspace_id=? and equipment_id=? order by started_at desc,id desc",w,equipment);}
    @Transactional public Map<String,Object> assign(Actor actor,UUID w,UUID equipment,Assignment input){access.equipment(actor,w,equipment,"EQUIPMENT_MANAGE");if(input==null)throw ApiException.invalid("حدد المؤسسة أو أزل التعيين");var eq=db.queryForList("select id from equipment where workspace_id=? and id=? for update",w,equipment);if(eq.isEmpty())throw ApiException.missing();UUID target=input.organizationId();if(target!=null){var org=db.queryForList("select archived_at from organization where workspace_id=? and id=? for share",w,target);if(org.isEmpty()||org.getFirst().get("archived_at")!=null)throw ApiException.missing();if(!access.organization(access.member(actor,w),w,target))throw ApiException.missing();}
        var current=db.queryForList("select id,organization_id from equipment_organization_assignment where workspace_id=? and equipment_id=? and ended_at is null for update",w,equipment);UUID old=current.isEmpty()?null:(UUID)current.getFirst().get("organization_id");if(Objects.equals(old,target)){Map<String,Object> same=new HashMap<>();same.put("equipmentId",equipment);same.put("organizationId",target);return same;}
        if(old!=null && Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from project_equipment_link l join project_or_contract p on p.workspace_id=l.workspace_id and p.id=l.project_id where l.workspace_id=? and l.equipment_id=? and l.unlinked_at is null and p.status='ACTIVE' and p.archived_at is null and p.organization_id=?)",Boolean.class,w,equipment,old)))throw new ApiException(409,"ACTIVE_ORGANIZATION_PROJECT","افصل المعدة من المشروع أو أكمله قبل تغيير مؤسستها");
        if(old!=null)db.update("update equipment_organization_assignment set ended_at=clock_timestamp() where id=?",current.getFirst().get("id"));if(target!=null)db.update("insert into equipment_organization_assignment(id,workspace_id,equipment_id,organization_id,assigned_by) values(?,?,?,?,?)",UUID.randomUUID(),w,equipment,target,actor.userId());audit.record(w,actor.userId(),old==null?"EQUIPMENT_ORGANIZATION_ASSIGNED":target==null?"EQUIPMENT_ORGANIZATION_UNASSIGNED":"EQUIPMENT_ORGANIZATION_MOVED",equipment);Map<String,Object> result=new HashMap<>();result.put("equipmentId",equipment);result.put("organizationId",target);return result;
    }
}
