package com.equipment.projects;

import com.equipment.audit.Audit;
import com.equipment.common.*;
import com.equipment.identity.Actor;
import com.equipment.workspaces.Access;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ProjectService {
    private final JdbcTemplate db;private final Access access;private final Audit audit;
    public ProjectService(JdbcTemplate db,Access access,Audit audit){this.db=db;this.access=access;this.audit=audit;}
    public record Input(String kind,String name,UUID organizationId,String clientName,String contractNumber,String startDate,String endDate,String notes){}
    private String optional(String value,int max){return value==null||value.isBlank()?null:Values.text(value,max,"النص");}
    private java.sql.Date date(String value){return value==null||value.isBlank()?null:java.sql.Date.valueOf(Values.date(value));}
    private void validate(Input in){if(in==null||!Set.of("PROJECT","CONTRACT").contains(in.kind()))throw ApiException.invalid("نوع السجل غير صالح");LocalDate start=in.startDate()==null||in.startDate().isBlank()?null:Values.date(in.startDate()),end=in.endDate()==null||in.endDate().isBlank()?null:Values.date(in.endDate());if(start!=null&&end!=null&&start.isAfter(end))throw ApiException.invalid("تاريخ البداية بعد النهاية");}
    private Map<String,Object> row(UUID w,UUID id){var rows=db.queryForList("select p.*,o.name as organization_name from project_or_contract p left join organization o on o.workspace_id=p.workspace_id and o.id=p.organization_id where p.workspace_id=? and p.id=?",w,id);if(rows.isEmpty())throw ApiException.missing();return rows.getFirst();}
    public Map<String,Object> get(Actor actor,UUID w,UUID id){access.project(actor,w,id,"PROJECT_VIEW");return row(w,id);}
    public List<Map<String,Object>> list(Actor actor,UUID w,boolean archived,String kind,String status,UUID organizationId,String search){
        Access.Member m=access.require(actor,w,"PROJECT_VIEW");
        if(kind!=null&&!Set.of("PROJECT","CONTRACT").contains(kind))throw ApiException.invalid("نوع السجل غير صالح");
        if(status!=null&&!Set.of("ACTIVE","COMPLETED").contains(status))throw ApiException.invalid("حالة المشروع غير صالحة");
        if(organizationId!=null&&(!access.organization(m,w,organizationId)||!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from organization where workspace_id=? and id=?)",Boolean.class,w,organizationId))))throw ApiException.missing();
        String term=search==null?"":search.trim();if(term.length()>100)throw ApiException.invalid("اختصر البحث");
        return db.queryForList("select * from project_or_contract where workspace_id=? and (archived_at is not null)=? and (?::varchar is null or kind=?) and (?::varchar is null or status=?) and (?::uuid is null or organization_id=?) and (position(lower(?) in lower(name))>0 or position(lower(?) in lower(coalesce(client_name,'')))>0 or position(lower(?) in lower(coalesce(contract_number,'')))>0) order by created_at desc limit 100",w,archived,kind,kind,status,status,organizationId,organizationId,term,term,term)
            .stream().filter(r->access.project(m,w,(UUID)r.get("id"))).toList();
    }
    @Transactional public Map<String,Object> create(Actor actor,UUID w,Input in){Access.Member m=access.require(actor,w,"PROJECT_MANAGE");validate(in);UUID org=in.organizationId();if(org!=null){if(!access.organization(m,w,org))throw ApiException.missing();var rows=db.queryForList("select archived_at from organization where workspace_id=? and id=? for share",w,org);if(rows.isEmpty()||rows.getFirst().get("archived_at")!=null)throw ApiException.missing();}else if(!m.scope().equals("ALL_EQUIPMENT"))throw ApiException.missing();UUID id=UUID.randomUUID();db.update("insert into project_or_contract(id,workspace_id,kind,name,organization_id,client_name,contract_number,start_date,end_date,notes,created_by) values(?,?,?,?,?,?,?,?,?,?,?)",id,w,in.kind(),Values.text(in.name(),100,"اسم المشروع أو العقد"),org,optional(in.clientName(),100),optional(in.contractNumber(),100),date(in.startDate()),date(in.endDate()),optional(in.notes(),1000),actor.userId());audit.record(w,actor.userId(),"PROJECT_CREATED",id);return row(w,id);}
    @Transactional public Map<String,Object> edit(Actor actor,UUID w,UUID id,Input in){access.project(actor,w,id,"PROJECT_MANAGE");validate(in);var locked=db.queryForList("select * from project_or_contract where workspace_id=? and id=? for update",w,id);if(locked.isEmpty())throw ApiException.missing();var old=locked.getFirst();if(old.get("archived_at")!=null)throw new ApiException(409,"PROJECT_ARCHIVED","المشروع مؤرشف");UUID org=in.organizationId();if(org!=null){if(!access.organization(access.member(actor,w),w,org))throw ApiException.missing();var rows=db.queryForList("select archived_at from organization where workspace_id=? and id=? for share",w,org);if(rows.isEmpty()||rows.getFirst().get("archived_at")!=null)throw ApiException.missing();}else if(!access.member(actor,w).scope().equals("ALL_EQUIPMENT"))throw ApiException.missing();if(!Objects.equals(old.get("organization_id"),org)&&(Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from project_equipment_link where workspace_id=? and project_id=? and unlinked_at is null)",Boolean.class,w,id))||Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from financial_entry where workspace_id=? and project_id=?)",Boolean.class,w,id))))throw new ApiException(409,"PROJECT_ORGANIZATION_LOCKED","افصل المعدات والعمليات المالية المصنفة قبل تغيير مؤسسة المشروع");db.update("update project_or_contract set kind=?,name=?,organization_id=?,client_name=?,contract_number=?,start_date=?,end_date=?,notes=? where workspace_id=? and id=?",in.kind(),Values.text(in.name(),100,"اسم المشروع أو العقد"),org,optional(in.clientName(),100),optional(in.contractNumber(),100),date(in.startDate()),date(in.endDate()),optional(in.notes(),1000),w,id);audit.record(w,actor.userId(),"PROJECT_UPDATED",id);return row(w,id);}
    @Transactional public Map<String,Object> transition(Actor actor,UUID w,UUID id,String action){access.project(actor,w,id,"PROJECT_MANAGE");var p=db.queryForList("select * from project_or_contract where workspace_id=? and id=? for update",w,id);if(p.isEmpty())throw ApiException.missing();var old=p.getFirst();switch(action){case "complete"->{if(old.get("archived_at")!=null||!"ACTIVE".equals(old.get("status")))throw new ApiException(409,"PROJECT_STATE","حالة المشروع لا تسمح");db.update("update project_equipment_link set unlinked_at=clock_timestamp() where workspace_id=? and project_id=? and unlinked_at is null",w,id);db.update("update project_or_contract set status='COMPLETED' where workspace_id=? and id=?",w,id);audit.record(w,actor.userId(),"PROJECT_COMPLETED",id);}case "reopen"->{if(old.get("archived_at")!=null||!"COMPLETED".equals(old.get("status")))throw new ApiException(409,"PROJECT_STATE","حالة المشروع لا تسمح");db.update("update project_or_contract set status='ACTIVE' where workspace_id=? and id=?",w,id);audit.record(w,actor.userId(),"PROJECT_REOPENED",id);}case "archive"->{if(old.get("archived_at")!=null)throw new ApiException(409,"PROJECT_STATE","المشروع مؤرشف");db.update("update project_equipment_link set unlinked_at=clock_timestamp() where workspace_id=? and project_id=? and unlinked_at is null",w,id);db.update("update project_or_contract set archived_at=now() where workspace_id=? and id=?",w,id);audit.record(w,actor.userId(),"PROJECT_ARCHIVED",id);}case "restore"->{if(old.get("archived_at")==null)throw new ApiException(409,"PROJECT_STATE","المشروع غير مؤرشف");if(old.get("organization_id")!=null){var organization=db.queryForList("select archived_at from organization where workspace_id=? and id=? for share",w,old.get("organization_id"));if(organization.isEmpty()||organization.getFirst().get("archived_at")!=null)throw new ApiException(409,"ORGANIZATION_ARCHIVED","استعد المؤسسة قبل المشروع");}db.update("update project_or_contract set archived_at=null where workspace_id=? and id=?",w,id);audit.record(w,actor.userId(),"PROJECT_RESTORED",id);}default->throw new IllegalArgumentException(action);}return row(w,id);}
    public List<Map<String,Object>> equipment(Actor actor,UUID w,UUID id){
        Access.Member member=access.require(actor,w,"PROJECT_VIEW");
        if(!access.project(member,w,id))throw ApiException.missing();
        return db.queryForList("select l.id,l.equipment_id,e.name equipment_name,l.linked_at,l.unlinked_at,l.linked_by from project_equipment_link l join equipment e on e.workspace_id=l.workspace_id and e.id=l.equipment_id where l.workspace_id=? and l.project_id=? order by l.linked_at desc,l.id desc",w,id)
            .stream().filter(link->access.contains(member,w,(UUID)link.get("equipment_id"))).toList();
    }
    public List<Map<String,Object>> activeForEquipment(Actor actor,UUID w,UUID equipment){
        access.equipment(actor,w,equipment,"EQUIPMENT_VIEW");
        Access.Member member=access.member(actor,w);
        if(!member.has("PROJECT_VIEW"))return List.of();
        return db.queryForList("select p.id,p.name,p.kind from project_equipment_link l join project_or_contract p on p.workspace_id=l.workspace_id and p.id=l.project_id where l.workspace_id=? and l.equipment_id=? and l.unlinked_at is null and p.status='ACTIVE' and p.archived_at is null order by p.name,p.id",w,equipment)
            .stream().filter(p->access.project(member,w,(UUID)p.get("id"))).toList();
    }
    @Transactional public Map<String,Object> link(Actor actor,UUID w,UUID id,UUID equipment){access.project(actor,w,id,"PROJECT_MANAGE");access.equipment(actor,w,equipment,"EQUIPMENT_VIEW");var p=db.queryForList("select * from project_or_contract where workspace_id=? and id=? for update",w,id);if(p.isEmpty())throw ApiException.missing();var row=p.getFirst();if(row.get("archived_at")!=null||!"ACTIVE".equals(row.get("status")))throw new ApiException(409,"PROJECT_INACTIVE","اربط المعدات بمشروع نشط فقط");var eq=db.queryForList("select id from equipment where workspace_id=? and id=? for update",w,equipment);if(eq.isEmpty())throw ApiException.missing();UUID org=(UUID)row.get("organization_id");if(org!=null&&!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from equipment_organization_assignment where workspace_id=? and equipment_id=? and organization_id=? and ended_at is null)",Boolean.class,w,equipment,org)))throw new ApiException(409,"PROJECT_ORGANIZATION_MISMATCH","المعدة لا تتبع مؤسسة المشروع الحالية");if(Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from project_equipment_link where workspace_id=? and project_id=? and equipment_id=? and unlinked_at is null)",Boolean.class,w,id,equipment)))throw new ApiException(409,"PROJECT_EQUIPMENT_LINKED","المعدة مرتبطة بالمشروع بالفعل");UUID link=UUID.randomUUID();db.update("insert into project_equipment_link(id,workspace_id,project_id,equipment_id,linked_by) values(?,?,?,?,?)",link,w,id,equipment,actor.userId());audit.record(w,actor.userId(),"PROJECT_EQUIPMENT_LINKED",link);return Map.of("id",link,"projectId",id,"equipmentId",equipment);}
    @Transactional public void unlink(Actor actor,UUID w,UUID id,UUID equipment){access.project(actor,w,id,"PROJECT_MANAGE");access.equipment(actor,w,equipment,"EQUIPMENT_VIEW");int changed=db.update("update project_equipment_link set unlinked_at=clock_timestamp() where workspace_id=? and project_id=? and equipment_id=? and unlinked_at is null",w,id,equipment);if(changed==0)throw ApiException.missing();audit.record(w,actor.userId(),"PROJECT_EQUIPMENT_UNLINKED",equipment);}
    public Map<String,String> summary(Actor actor,UUID w,UUID id){
        access.project(actor,w,id,"PROJECT_VIEW");
        Access.Member member=access.require(actor,w,"FINANCE_VIEW");
        String scope=member.scope().equals("ALL_EQUIPMENT")?"":" and "+access.financialPredicate(member);
        List<Object> args=new ArrayList<>(List.of(w,id));
        if(!scope.isEmpty())Collections.addAll(args,access.financialScopeArgs(member));
        String where=" where f.workspace_id=? and f.project_id=? and f.lifecycle='POSTED'"+scope;
        var amounts=db.queryForMap("select coalesce(sum(case when f.entry_type='INCOME' then f.amount end),0) income,coalesce(sum(case when f.entry_type='EXPENSE' then f.amount end),0) expense from financial_entry f"+where,args.toArray());
        var cash=db.queryForMap("select coalesce(sum(case when f.entry_type='INCOME' then s.amount end),0) collected,coalesce(sum(case when f.entry_type='EXPENSE' then s.amount end),0) paid from financial_entry f left join settlement s on s.workspace_id=f.workspace_id and s.entry_id=f.id"+where,args.toArray());
        var refunds=db.queryForMap("select coalesce(sum(case when f.entry_type='INCOME' then r.amount end),0) income_refunds,coalesce(sum(case when f.entry_type='EXPENSE' then r.amount end),0) expense_refunds from financial_entry f left join financial_refund r on r.workspace_id=f.workspace_id and r.entry_id=f.id"+where,args.toArray());
        BigDecimal income=(BigDecimal)amounts.get("income"),expense=(BigDecimal)amounts.get("expense"),collected=((BigDecimal)cash.get("collected")).subtract((BigDecimal)refunds.get("income_refunds")),paid=((BigDecimal)cash.get("paid")).subtract((BigDecimal)refunds.get("expense_refunds"));
        return Map.of("recordedIncome",money(income),"recordedExpenses",money(expense),"recordedDifference",money(income.subtract(expense)),"collected",money(collected),"paid",money(paid),"receivablesRemaining",money(income.subtract(collected)),"payablesRemaining",money(expense.subtract(paid)));
    }
    private String money(BigDecimal amount){return amount.setScale(2).toPlainString();}

}
