package com.equipment.workspaces;

import com.equipment.audit.Audit;
import com.equipment.common.*;
import com.equipment.identity.*;
import java.sql.Array;
import java.sql.SQLException;
import java.time.*;
import java.util.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class TeamService {
    private final JdbcTemplate db;private final Access access;private final Audit audit;
    public TeamService(JdbcTemplate db,Access access,Audit audit){this.db=db;this.access=access;this.audit=audit;}
    public record Invite(String displayName,String phone,String role,String scope,List<UUID> equipmentIds,Set<String> capabilities,String financialMode,List<UUID> organizationIds){public Invite(String displayName,String phone,String role,String scope,List<UUID> equipmentIds,Set<String> capabilities,String financialMode){this(displayName,phone,role,scope,equipmentIds,capabilities,financialMode,null);}}
    public record MemberChange(String role,String scope,List<UUID> equipmentIds,Set<String> capabilities,String financialMode,List<UUID> organizationIds){public MemberChange(String role,String scope,List<UUID> equipmentIds,Set<String> capabilities,String financialMode){this(role,scope,equipmentIds,capabilities,financialMode,null);}}
    private String role(String value){if(!Set.of("MANAGER","ACCOUNTANT","DRIVER").contains(value))throw ApiException.invalid("الدور غير صالح");return value;}
    private String scope(String role,String value){if(role.equals("DRIVER")){if(value!=null&&!value.equals("ASSIGNED_EQUIPMENT"))throw ApiException.invalid("نطاق السائق يتحدد بالتعيين");return "ASSIGNED_EQUIPMENT";}if(value==null)return "ALL_EQUIPMENT";if(!Set.of("ALL_EQUIPMENT","SELECTED_EQUIPMENT","SELECTED_ORGANIZATIONS").contains(value))throw ApiException.invalid("نطاق المعدات غير صالح");return value;}
    private String mode(String role,String value){String mode=value==null?(role.equals("DRIVER")?"REVIEW":"DIRECT"):value;if(!Set.of("DIRECT","REVIEW").contains(mode))throw ApiException.invalid("طريقة المالية غير صالحة");return mode;}
    private Set<String> caps(String role,Set<String> value){Set<String> result=value==null?Access.defaults(role):Set.copyOf(value);if(!Access.CAPABILITIES.containsAll(result))throw ApiException.invalid("الصلاحيات غير صالحة");return result;}
    private void owner(Actor actor,UUID w){access.owner(actor,w);}
    private void equipmentScope(UUID w,String scope,List<UUID> ids){if(scope.equals("SELECTED_EQUIPMENT")){if(ids==null||ids.isEmpty())throw ApiException.invalid("اختر معدة واحدة على الأقل");for(UUID id:ids){Boolean exists=db.queryForObject("select exists(select 1 from equipment where workspace_id=? and id=?)",Boolean.class,w,id);if(!Boolean.TRUE.equals(exists))throw ApiException.missing();}}else if(ids!=null&&!ids.isEmpty())throw ApiException.invalid("قائمة المعدات لا تناسب النطاق");}
    private void organizationScope(UUID w,String scope,List<UUID> ids){if(scope.equals("SELECTED_ORGANIZATIONS")){if(ids==null||ids.isEmpty())throw ApiException.invalid("اختر مؤسسة واحدة على الأقل");for(UUID id:ids){Boolean exists=db.queryForObject("select exists(select 1 from organization where workspace_id=? and id=? and archived_at is null)",Boolean.class,w,id);if(!Boolean.TRUE.equals(exists))throw ApiException.missing();}}else if(ids!=null&&!ids.isEmpty())throw ApiException.invalid("قائمة المؤسسات لا تناسب النطاق");}
    private String[] array(Set<String> caps){return caps.toArray(String[]::new);}
    private Map<String,Object> present(Map<String,Object> row){Map<String,Object> result=new LinkedHashMap<>();row.forEach((key,value)->{StringBuilder name=new StringBuilder();boolean upper=false;for(char c:key.toCharArray()){if(c=='_'){upper=true;continue;}name.append(upper?Character.toUpperCase(c):c);upper=false;}result.put(name.toString(),value instanceof java.sql.Timestamp timestamp?timestamp.toInstant().toString():value);});return result;}
    @Transactional public Map<String,Object> invite(Actor actor,UUID w,Invite input){owner(actor,w);if(input==null)throw ApiException.invalid("أدخل بيانات الدعوة");String phone=IdentityService.normalizePhone(input.phone()),name=Values.text(input.displayName(),100,"اسم العضو"),role=role(input.role()),scope=scope(role,input.scope()),mode=mode(role,input.financialMode());Set<String> capabilities=caps(role,input.capabilities());equipmentScope(w,scope,input.equipmentIds());organizationScope(w,scope,input.organizationIds());
        db.queryForList("select pg_advisory_xact_lock(hashtextextended(?,0))","invite:"+w+":"+phone);
        Boolean active=db.queryForObject("select exists(select 1 from membership m join app_user u on u.id=m.user_id where m.workspace_id=? and u.phone=? and m.active)",Boolean.class,w,phone);if(Boolean.TRUE.equals(active))throw new ApiException(409,"ALREADY_MEMBER","العضو موجود بالفعل");
        db.update("update workspace_invitation set status='CANCELLED',decided_at=now() where workspace_id=? and phone=? and status='PENDING' and expires_at<=now()",w,phone);
        Boolean pending=db.queryForObject("select exists(select 1 from workspace_invitation where workspace_id=? and phone=? and status='PENDING')",Boolean.class,w,phone);if(Boolean.TRUE.equals(pending))throw new ApiException(409,"INVITATION_PENDING","توجد دعوة معلقة لهذا الرقم");
        UUID id=UUID.randomUUID();db.update("insert into workspace_invitation(id,workspace_id,phone,display_name,role,capabilities,scope,financial_mode,invited_by) values(?,?,?,?,?,?,?,?,?)",id,w,phone,name,role,array(capabilities),scope,mode,actor.userId());if(scope.equals("SELECTED_EQUIPMENT"))for(UUID equipment:new HashSet<>(input.equipmentIds()))db.update("insert into invitation_equipment(invitation_id,workspace_id,equipment_id) values(?,?,?)",id,w,equipment);if(scope.equals("SELECTED_ORGANIZATIONS"))for(UUID organization:new HashSet<>(input.organizationIds()))db.update("insert into invitation_organization(invitation_id,workspace_id,organization_id) values(?,?,?)",id,w,organization);audit.record(w,actor.userId(),"INVITATION_CREATED",id);return invitation(id);
    }
    private Map<String,Object> invitation(UUID id){var r=db.queryForMap("select i.id,i.workspace_id,i.phone,i.display_name,i.role,i.scope,i.financial_mode,i.status,i.created_at,i.expires_at,w.name as workspace_name from workspace_invitation i join workspace w on w.id=i.workspace_id where i.id=?",id);return present(r);}
    public List<Map<String,Object>> invitations(Actor actor,UUID w){owner(actor,w);return db.queryForList("select id,phone,display_name,role,scope,financial_mode,status,created_at,expires_at from workspace_invitation where workspace_id=? order by created_at desc limit 100",w).stream().map(this::present).toList();}
    public List<Map<String,Object>> pendingForAccount(Actor actor){return db.queryForList("select i.id,i.workspace_id,w.name as workspace_name,i.display_name,i.role,i.expires_at,u.name as inviter_name from workspace_invitation i join workspace w on w.id=i.workspace_id join app_user u on u.id=i.invited_by join app_user self on self.phone=i.phone where self.id=? and i.status='PENDING' and i.expires_at>now() order by i.created_at desc limit 100",actor.userId()).stream().map(this::present).toList();}
    @Transactional public Map<String,Object> resend(Actor actor,UUID w,UUID id){owner(actor,w);var row=db.queryForList("select * from workspace_invitation where workspace_id=? and id=? for update",w,id);if(row.isEmpty())throw ApiException.missing();var old=row.getFirst();if(!"PENDING".equals(old.get("status")))throw new ApiException(409,"INVITATION_CLOSED","الدعوة مغلقة");db.update("update workspace_invitation set expires_at=now()+interval '7 days',created_at=now() where id=?",id);audit.record(w,actor.userId(),"INVITATION_RESENT",id);return invitation(id);}
    @Transactional public Map<String,Object> cancel(Actor actor,UUID w,UUID id){owner(actor,w);int n=db.update("update workspace_invitation set status='CANCELLED',decided_at=now() where workspace_id=? and id=? and status='PENDING'",w,id);if(n==0)throw new ApiException(409,"INVITATION_CLOSED","الدعوة مغلقة");audit.record(w,actor.userId(),"INVITATION_CANCELLED",id);return invitation(id);}
    @Transactional public Map<String,Object> decide(Actor actor,UUID id,boolean accept){var rows=db.queryForList("select i.* from workspace_invitation i join app_user u on u.phone=i.phone where i.id=? and u.id=? for update of i",id,actor.userId());if(rows.isEmpty())throw ApiException.missing();var i=rows.getFirst();UUID w=(UUID)i.get("workspace_id");if(!"PENDING".equals(i.get("status"))||((java.sql.Timestamp)i.get("expires_at")).toInstant().isBefore(Instant.now()))throw new ApiException(409,"INVITATION_CLOSED","الدعوة مغلقة أو انتهت");
        if(!accept){db.update("update workspace_invitation set status='DECLINED',decided_at=now() where id=?",id);audit.record(w,actor.userId(),"INVITATION_DECLINED",id);return invitation(id);}
        var existing=db.queryForList("select active,role from membership where workspace_id=? and user_id=? for update",w,actor.userId());if(!existing.isEmpty()&&Boolean.TRUE.equals(existing.getFirst().get("active")))throw new ApiException(409,"ALREADY_MEMBER","العضو موجود بالفعل");
        String role=(String)i.get("role"),scope=(String)i.get("scope"),mode=(String)i.get("financial_mode");Object capabilities=i.get("capabilities");
        if(existing.isEmpty())db.update("insert into membership(workspace_id,user_id,role,active,display_name,capabilities,scope,financial_mode) values(?,?,?,true,?,?,?,?)",w,actor.userId(),role,i.get("display_name"),capabilities,scope,mode);
        else db.update("update membership set active=true,revoked_at=null,role=?,display_name=?,capabilities=?,scope=?,financial_mode=? where workspace_id=? and user_id=?",role,i.get("display_name"),capabilities,scope,mode,w,actor.userId());
        db.update("delete from membership_equipment where workspace_id=? and user_id=?",w,actor.userId());if(scope.equals("SELECTED_EQUIPMENT"))db.update("insert into membership_equipment(workspace_id,user_id,equipment_id) select workspace_id,?,equipment_id from invitation_equipment where invitation_id=?",actor.userId(),id);
        db.update("delete from membership_organization where workspace_id=? and user_id=?",w,actor.userId());if(scope.equals("SELECTED_ORGANIZATIONS"))db.update("insert into membership_organization(workspace_id,user_id,organization_id) select workspace_id,?,organization_id from invitation_organization where invitation_id=?",actor.userId(),id);
        db.update("update workspace_invitation set status='ACCEPTED',decided_at=now() where id=?",id);audit.record(w,actor.userId(),"INVITATION_ACCEPTED",id);return invitation(id);
    }
    public List<Map<String,Object>> members(Actor actor,UUID w){access.require(actor,w,"TEAM_MANAGE");return db.queryForList("select m.user_id,coalesce(m.display_name,u.name) as display_name,u.phone,m.role,m.active,m.scope,m.financial_mode from membership m join app_user u on u.id=m.user_id where m.workspace_id=? order by m.active desc,m.role='OWNER' desc,m.display_name nulls last limit 100",w).stream().map(this::present).toList();}
    public Map<String,Object> member(Actor actor,UUID w,UUID user){access.require(actor,w,"TEAM_MANAGE");var rows=db.queryForList("select m.user_id,coalesce(m.display_name,u.name) as display_name,u.phone,m.role,m.active,m.scope,m.financial_mode,m.capabilities from membership m join app_user u on u.id=m.user_id where m.workspace_id=? and m.user_id=?",w,user);if(rows.isEmpty())throw ApiException.missing();Map<String,Object> result=present(rows.getFirst());result.put("capabilities","OWNER".equals(rows.getFirst().get("role"))?Access.CAPABILITIES:sqlCaps(rows.getFirst().get("capabilities")));result.put("equipmentIds",selected(w,user));result.put("organizationIds",selectedOrganizations(w,user));return result;}
    @Transactional public Map<String,Object> change(Actor actor,UUID w,UUID user,MemberChange input){owner(actor,w);if(input==null)throw ApiException.invalid("أدخل التغييرات");var rows=db.queryForList("select * from membership where workspace_id=? and user_id=? for update",w,user);if(rows.isEmpty()||"OWNER".equals(rows.getFirst().get("role")))throw ApiException.missing();var old=rows.getFirst();String role=input.role()==null?(String)old.get("role"):role(input.role());String scope=input.scope()==null?(role.equals("DRIVER")?"ASSIGNED_EQUIPMENT":"DRIVER".equals(old.get("role"))?"ALL_EQUIPMENT":(String)old.get("scope")):scope(role,input.scope());if(role.equals("DRIVER"))scope="ASSIGNED_EQUIPMENT";String mode=input.financialMode()==null?(role.equals(old.get("role"))?(String)old.get("financial_mode"):mode(role,null)):mode(role,input.financialMode());Set<String> capabilities=caps(role,input.capabilities()==null&&role.equals(old.get("role"))?sqlCaps(old.get("capabilities")):input.capabilities());equipmentScope(w,scope,input.equipmentIds()==null&&scope.equals(old.get("scope"))?selected(w,user):input.equipmentIds());organizationScope(w,scope,input.organizationIds()==null&&scope.equals(old.get("scope"))?selectedOrganizations(w,user):input.organizationIds());
        if(!role.equals("DRIVER"))db.update("update driver_assignment set ended_at=now() where workspace_id=? and driver_user_id=? and ended_at is null",w,user);
        List<UUID> selected=input.equipmentIds()==null?selected(w,user):input.equipmentIds();
        List<UUID> selectedOrganizations=input.organizationIds()==null?selectedOrganizations(w,user):input.organizationIds();
        Set<String> previousCaps=sqlCaps(old.get("capabilities"));List<UUID> previousSelected=selected(w,user),previousOrganizations=selectedOrganizations(w,user);
        db.update("update membership set role=?,scope=?,financial_mode=?,capabilities=? where workspace_id=? and user_id=?",role,scope,mode,array(capabilities),w,user);db.update("delete from membership_equipment where workspace_id=? and user_id=?",w,user);if(scope.equals("SELECTED_EQUIPMENT"))for(UUID equipment:new HashSet<>(selected))db.update("insert into membership_equipment(workspace_id,user_id,equipment_id) values(?,?,?)",w,user,equipment);
        db.update("delete from membership_organization where workspace_id=? and user_id=?",w,user);if(scope.equals("SELECTED_ORGANIZATIONS"))for(UUID organization:new HashSet<>(selectedOrganizations))db.update("insert into membership_organization(workspace_id,user_id,organization_id) values(?,?,?)",w,user,organization);
        if(!role.equals(old.get("role")))audit.record(w,actor.userId(),"MEMBER_ROLE_CHANGED",user);
        if(!capabilities.equals(previousCaps))audit.record(w,actor.userId(),"MEMBER_PERMISSIONS_CHANGED",user);
        if(!scope.equals(old.get("scope"))||!new HashSet<>(selected).equals(new HashSet<>(previousSelected))||!new HashSet<>(selectedOrganizations).equals(new HashSet<>(previousOrganizations)))audit.record(w,actor.userId(),"MEMBER_SCOPE_CHANGED",user);
        if(!mode.equals(old.get("financial_mode")))audit.record(w,actor.userId(),"MEMBER_FINANCIAL_MODE_CHANGED",user);
        return member(actor,w,user);
    }
    private Set<String> sqlCaps(Object value){if(value instanceof Array a)try{return Set.of((String[])a.getArray());}catch(SQLException e){throw new IllegalStateException(e);}return Set.of();}
    private List<UUID> selected(UUID w,UUID user){return db.queryForList("select equipment_id from membership_equipment where workspace_id=? and user_id=?",w,user).stream().map(r->(UUID)r.get("equipment_id")).toList();}
    private List<UUID> selectedOrganizations(UUID w,UUID user){return db.queryForList("select organization_id from membership_organization where workspace_id=? and user_id=?",w,user).stream().map(r->(UUID)r.get("organization_id")).toList();}
    @Transactional public void revoke(Actor actor,UUID w,UUID user){owner(actor,w);int n=db.update("update membership set active=false,revoked_at=now() where workspace_id=? and user_id=? and role<>'OWNER' and active=true",w,user);if(n==0)throw ApiException.missing();db.update("update driver_assignment set ended_at=now() where workspace_id=? and driver_user_id=? and ended_at is null",w,user);audit.record(w,actor.userId(),"MEMBER_REVOKED",user);}
    public List<Map<String,Object>> workspaces(Actor actor){return db.queryForList("select w.id,w.name,m.role,m.scope,m.financial_mode from membership m join workspace w on w.id=m.workspace_id where m.user_id=? and m.active order by w.created_at",actor.userId()).stream().map(this::present).toList();}
    @Transactional public void selectWorkspace(Actor actor,UUID w){access.member(actor,w);db.update("update app_user set last_workspace_id=? where id=?",w,actor.userId());}
}
